
services:
  - type: web
    name: gamessince-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: cron
    name: gamessince-cron
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python rebuild_cache.py
    schedule: "0 9 * * *"
